# Generated by Django 4.0.3 on 2022-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
